automation:
#  - alias: Charge Solar Battery From Grid
#    id: charge_solar_battery_from_grid
#    description: ""
#    mode: single
#    trigger:
#      - platform: state
#        entity_id:
#          - select.solar_imported_power_daily
#        to: offpeak
#    condition:
#      - condition: and
#        conditions:
#          - condition: state
#            entity_id: select.solar_imported_power_daily
#            state: offpeak
#          - type: is_battery_level
#            condition: device
#            device_id: 80ff50611df8b41939dcd5f83a403c71
#            entity_id: dd6cbd14d01a24feac5474d7d78addec
#            domain: sensor
#            below: 100
#    action:
#      - service: select.select_option
#        data:
#          option: Charge from Solar Power and Grid
#        target:
#          entity_id: select.solaredge_i1_storage_default_mode
#      - service: select.select_option
#        data:
#          option: Always Allowed
#        target:
#          entity_id: select.solaredge_i1_ac_charge_policy

  - alias: Discharge Solar Battery
    id: discharge_solar_battery
    description: "Export Battery to Grid"
    mode: single
    trigger:
    - platform: numeric_state
      entity_id: sensor.solaredge_b1_state_of_energy
      above: 98
    condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.import_profitable
          state: "on"
        - condition: state
          entity_id: select.solar_house_consumption_daily
          state: offpeak
        - condition: time
          before: "07:00:00"
    action:
    - service: select.select_option
      data:
        option: Discharge to Maximize Export
      target:
        entity_id: select.solaredge_i1_storage_command_mode
  - alias: Disable Solar Battery
    id: disable_solar_battery
    description: ""
    mode: single
    trigger:
    - platform: numeric_state
      entity_id: sensor.solaredge_b1_state_of_energy
      above: 99
    condition:
    - condition: and
      conditions:
#        - condition: state
#          entity_id: binary_sensor.import_profitable
#          state: "off"
        - condition: state
          entity_id: select.solar_imported_power_daily
          state: offpeak
    action:
    - service: select.select_option
      data:
        option: Solar Power Only (Off)
      target:
        entity_id: select.solaredge_i1_storage_default_mode
  - alias: Charge Solar Battery From PV Only
    id: charge_solar_battery_from_pv_only
    description: ""
    mode: single
    trigger:
      - platform: state
        entity_id:
          - select.solar_imported_power_daily
        to: peak
    condition: []
    action:
      - service: select.select_option
        data:
          option: Maximize Self Consumption
        target:
          entity_id: select.solaredge_i1_storage_default_mode
      - service: select.select_option
        data:
          option: Disabled
        target:
          entity_id: select.solaredge_i1_ac_charge_policy
  - alias: Notify Battery Not Charging
    id: notify_battery_not_charging
    description: ""
    mode: single
    trigger:
      - platform: time
        at: "01:05:00"
    condition:
      - condition: or
        conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: select.solaredge_i1_ac_charge_policy
                state: Always Allowed
          - condition: not
            conditions:
              - condition: state
                entity_id: select.solaredge_i1_storage_default_mode
                state: Charge from Solar Power and Grid
    action:
      - device_id: 13b654b925b2c03ce401d52f06a3ece4
        domain: mobile_app
        type: notify
        message: Battery Not Charging
        title: Battery Not Charging
      - device_id: 8fef5f1ad91932a774d80b78e7798b3d
        domain: mobile_app
        type: notify
        message: Battery Not Charging
        title: Battery Not Charging

  - alias: Charge Solar Battery From Grid_rerun
    id: charge_solar_battery_from_grid_rerun
    description: ""
    mode: single
    trigger:
      - platform: time
        at: "04:00:00"
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: select.solar_imported_power_daily
            state: offpeak
          - type: is_battery_level
            condition: device
            device_id: 80ff50611df8b41939dcd5f83a403c71
            entity_id: dd6cbd14d01a24feac5474d7d78addec
            domain: sensor
            below: 100
      - condition: or
        conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: select.solaredge_i1_storage_default_mode
                state: Charge from Solar Power and Grid
          - condition: not
            conditions:
              - condition: state
                entity_id: select.solaredge_i1_ac_charge_policy
                state: Always Allowed
    action:
      - service: select.select_option
        data:
          option: Charge from Solar Power and Grid
        target:
          entity_id: select.solaredge_i1_storage_default_mode
      - service: select.select_option
        data:
          option: Always Allowed
        target:
          entity_id: select.solaredge_i1_ac_charge_policy

